#!/usr/bin/python3

def raise_exception():
    num1 = 5
    num2 = "2"
    result = num1 + num2
